# Generated by Django 3.2 on 2024-10-28 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('duracion_estancia', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
